/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_glorantq_aboe_chat_client_notification_WindowsToastNotifier */

#ifndef _Included_me_glorantq_aboe_chat_client_notification_WindowsToastNotifier
#define _Included_me_glorantq_aboe_chat_client_notification_WindowsToastNotifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_glorantq_aboe_chat_client_notification_WindowsToastNotifier
 * Method:    initialise
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_me_glorantq_aboe_chat_client_notification_WindowsToastNotifier_initialise
  (JNIEnv *, jobject);

/*
 * Class:     me_glorantq_aboe_chat_client_notification_WindowsToastNotifier
 * Method:    showNotificationNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_glorantq_aboe_chat_client_notification_WindowsToastNotifier_showNotificationNative
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
